ktor:
    application:
        modules:
            - ru.eden.ApplicationKt.module
    deployment:
        port: 8080
        databaseURL: $DATABASE_URL
        databaseUser: $DATABASE_USER
        databasePassword: $DATABASE_PASSWORD